name : Build and package Roberta-sentencing to Dockerhub

on :
  # Trigger the workflow on push or pull requests events on the main branch
  push:
    branches : [webapp]

  # Allows you to run this workflow manually from the Actions tab:   #add comment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Upgrade Azure cli
        run: az upgrade

      - name: Adding extension
        run: az extension add --name ml

      - name: set auto-install of extensions
        run: az config set extension.use_dynamic_install=yes_without_prompt

      - name: attach workspace
        run: az ml folder attach -w "ml-ws" -g "practical-mlops"

      - name: retrieve the model
        run: az ml model download -t "." --model-id "roberta-sequence:1"

      - name: build flask-app container
        uses: docker/build-push-action@v2 #this is a comment
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: alfredodeza/flask-roberta:latest
